<?php
include "header.phtml";
?>
        <section>
            <div class="container">
                <div class="entry-list single">
                    <article>
                        <h1><?php
                                if(isset($post)){
                                    echo $post['title'];
                                }
                            ?></h1>
                        <time datetime='<?php
                            if(isset($post)){
                                echo $post['date'];
                            }
                        ?>'>
                            <?php
                            if(isset($post)){
                                echo $post['date'];
                            }
                            ?>
                        </time>
                        <div class="entry">
                            <p><?php
                                    if (isset($post)){
                                        echo $post['body'];
                                    }
                                ?></p>
                            <h4>Tags: </h4>
                            <?php
                            if(isset($tags)){
                                foreach ($tags as $tag){
                                    echo "<label>" .$tag['name']. "</label><input type='checkbox' name='tags' disabled value='" . $tag['name'] . "'";
                                    if (isset($selected_tags)){
                                        foreach ($selected_tags as $selected){
                                            if ($selected['name'] == $tag['name']){
                                                echo " checked";
                                            }
                                        }
                                    }
                                    echo " /><br>";
                                }
                            }
                            ?>

                            <p><a class="link" href="/edit/<?php
                                    if (isset($post)){
                                        echo $post['id'];
                                    }
                                ?>">Edit Entry</a></p>
                        </div>
                    </article>
                </div>
            </div>
        </section>
        <section class="entry-comments">
            <div class="container">
                <h2>Comments</h2>
                <?php
                    if (isset($comments)){
                        foreach ($comments as $comment){
                            echo "<div class=\"comment\">";
                            echo "<strong>" . $comment['name'] . "</strong>";

                            echo "<p>" . $comment['body'] . "</p>";
                            echo "</div>";
                        }
                    }
                ?>
                <div class="new-comment">
                    <form action="/detail/<?php echo $post['id'];?>" method="post">
                        <input type="hidden" name="post_id" value="2" />
                      <label for="name"> Name</label>
                      <input type="text" name="name"><br>
                      <label for="comment">Comment</label>
                      <textarea rows="5" name="body"></textarea>
                      <input type="submit" value="Post Comment" class="button">
                    </form>
                </div>
            </div>
        </section>
<?php include 'footer.phtml';?>