<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>SparkBlog</title>
        <link href='https://fonts.googleapis.com/css?family=Noto+Serif:400,400italic,700|Noto+Sans:700,400' rel='stylesheet' type='text/css'>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="../public/css/normalize.css">
        <link rel="stylesheet" href="../public/css/site.css">
    </head>
    <body>
        <header>
            <div class="container">
                <div class="site-header">
                    <a class="logo" href="index.phtml">SparkBlog</a>
                    <a class="new-entry button button-round" href="new.phtml"><i class="material-icons">create</i></a>
                </div>
            </div>
        </header>
        <section>
            <div class="container">
                <div class="edit-entry">
                    <h2>Edit Entry</h2>
                    <form action="/edit/<?php
                    if (isset($post)){
                        echo $post['id'];
                    }
                    ?>" method="post">
                        <label for="title"> Title</label>
                        <input type="text" name="title" value="<?php
                            if (isset($post)){
                                echo $post['title'];
                            }
                        ?>"><br>
                        <label for="entry">Entry</label>
                        <textarea rows="5" name="body"><?php
                            if (isset($post)){
                                echo $post['title'];
                            }
                            ?></textarea>
                        <input type="submit" value="Save Entry" class="button">
                        <a href="/edit/<?php
                        if (isset($post)){
                            echo $post['id'];
                        }
                        ?>" class="button button-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </section>
        <footer>
            <div>
                <a href="#">Contact Us</a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                <a href="#">Terms</a>
            </div>
        </footer>
    </body>
</html>