<?php
include "header.phtml";
?>
        <section>
            <div class="container">
                <div class="edit-entry">
                    <h2>Edit Entry</h2>
                    <form action="/edit/<?php
                    if (isset($post)){
                        echo $post['id'];
                    }
                    ?>" method="post">
                        <label for="title"> Title</label>
                        <input type="text" name="title" value="<?php
                            if (isset($post)){
                                echo $post['title'];
                            }
                        ?>"><br>
                        <label for="entry">Entry</label>
                        <textarea rows="5" name="body"><?php
                            if (isset($post)){
                                echo $post['title'];
                            }
                            ?></textarea>
                        <input type="submit" value="Save Entry" class="button">
                        <a href="/edit/<?php
                        if (isset($post)){
                            echo $post['id'];
                        }
                        ?>" class="button button-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </section>
<?php include 'footer.phtml';?>