<?php
include "header.phtml";
?>
        <section>
            <div class="container">
                <div class="entry-list">
                    <?php
                        if(isset($posts)){
                            foreach ($posts as $post){
                                echo "<article>";
                                echo "<h2><a href='detail/" . $post['id'] . "'>" . $post['title'] . "</a></h2>";
                                echo "<time datetime='" .$post['date']. "'>" . $post['date'] . "</time>";
                                echo "</article>";
                            }
                        }
                    ?>
                </div>
            </div>
        </section>

<?php include 'footer.phtml';?>