<?php
include "header.phtml";
?>
        <section>
            <div class="container">
                <div class="new-entry">
                    <h2>Publish New Entry</h2>
                    <form action="/new" method="post">
                        <label for="title"> Title</label>
                        <input type="text" name="title"><br>
                        <label for="date"> Date</label>
                        <input type="date" name="date"><br>
                        <label for="entry">Entry</label>
                        <textarea rows="5" name="body"></textarea>
                        <h4>Tags: </h4>
                        <?php
                        if (isset($tags)){
                            foreach ($tags as $tag){
                                echo "<label>" .$tag['name']. "</label><input type='checkbox' name='tags[]' value='" . $tag['id'] . "' />";
                            }
                        }
                        echo "<br><br>";
                        ?>
                        <input type="submit" value="Publish Entry" class="button">
                        <a href="/" class="button button-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </section>
<?php include 'footer.phtml';?>